"""Phase 2: bigram baseline.

1. Count every pair of consecutive characters -> the best possible bigram.
2. Train a (V, V) table by gradient descent and watch it approach that number.
3. Peek inside the learned table and generate text.

Usage:
    .venv/bin/python phase2.py
"""

import argparse
import math
import time

import torch

from bigram import BigramLM
from dataset import get_batch, load_data, pick_device


def section(title):
    print(f"\n{'=' * 70}\n{title}\n{'=' * 70}")


@torch.no_grad()
def estimate_loss(model, splits, batch_size, block_size, iters, device):
    """Average loss over `iters` random batches of each split (less noisy than one batch)."""
    model.eval()
    out = {}
    for name, data in splits.items():
        losses = torch.zeros(iters)  # (iters,)
        for k in range(iters):
            x, y = get_batch(data, batch_size, block_size, device)  # (B, T), (B, T)
            _, loss = model(x, y)
            losses[k] = loss.item()
        out[name] = losses.mean().item()
    model.train()
    return out


def count_bigram_loss(train, val, V):
    """The best bigram: probability of b after a = count(a,b) / count(a, anything)."""
    counts = torch.zeros(V, V)  # (V, V)
    pairs = train[:-1] * V + train[1:]  # (N-1,) each pair (a, b) encoded as one int a*V+b
    counts += torch.bincount(pairs, minlength=V * V).view(V, V).float()  # (V*V,) -> (V, V)

    probs = (counts + 1) / (counts + 1).sum(dim=1, keepdim=True)  # (V, V); +1 so no pair has prob 0

    def loss_on(data):
        p = probs[data[:-1], data[1:]]  # (N-1,) prob of each actual next char
        return -p.log().mean().item()

    return loss_on(train), loss_on(val), probs


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--device", default="auto")
    ap.add_argument("--batch-size", type=int, default=32)
    ap.add_argument("--block-size", type=int, default=128)
    ap.add_argument("--steps", type=int, default=3000)
    ap.add_argument("--lr", type=float, default=50.0, help="learning rate (plain SGD)")
    ap.add_argument("--eval-every", type=int, default=300)
    ap.add_argument("--eval-iters", type=int, default=50)
    ap.add_argument("--seed", type=int, default=1337)
    args = ap.parse_args()

    device = pick_device(args.device)
    torch.manual_seed(args.seed)
    tok, train, val = load_data()
    V = tok.vocab_size

    # ------------------------------------------------------------------
    section("1. Reference numbers")
    count_train, count_val, count_probs = count_bigram_loss(train, val, V)
    print(f"uniform guess (knows nothing)      : {math.log(V):.4f}")
    print(f"bigram by counting  train / val    : {count_train:.4f} / {count_val:.4f}")

    # ------------------------------------------------------------------
    section(f"2. Training the (V, V) table with SGD on {device}")
    model = BigramLM(V).to(device)
    n_params = sum(p.numel() for p in model.parameters())
    print(f"parameters: {n_params:,} (= {V} x {V})")
    splits = {"train": train, "val": val}
    t0 = time.perf_counter()
    for step in range(args.steps + 1):
        if step % args.eval_every == 0:
            l = estimate_loss(model, splits, args.batch_size, args.block_size, args.eval_iters, device)
            print(f"step {step:>5} | train {l['train']:.4f} | val {l['val']:.4f} | {time.perf_counter() - t0:5.1f}s")
        if step == args.steps:
            break

        x, y = get_batch(train, args.batch_size, args.block_size, device)  # (B, T), (B, T)
        _, loss = model(x, y)  # forward: scalar loss

        model.zero_grad(set_to_none=True)
        loss.backward()  # table.grad: (V, V), how the loss changes when each score changes
        with torch.no_grad():
            for p in model.parameters():
                p -= args.lr * p.grad  # plain SGD: step against the gradient

    # ------------------------------------------------------------------
    section("3. Looking inside the learned table")
    learned = torch.softmax(model.table.detach().cpu(), dim=-1)  # (V, V) scores -> probabilities
    for ch in ["q", "ç", ".", "\n"]:
        i = tok.stoi[ch]
        top = torch.topk(learned[i], 5)  # values: (5,), indices: (5,)
        guesses = "  ".join(f"{tok.itos[j]!r} {v:.0%}" for v, j in zip(top.values.tolist(), top.indices.tolist()))
        print(f"after {ch!r:>5}: {guesses}")

    # ------------------------------------------------------------------
    section("4. Text generated by the bigram (500 chars)")
    torch.manual_seed(args.seed)
    start = torch.tensor([[tok.stoi["\n"]]], device=device)  # (1, 1)
    print(tok.decode(model.generate(start, 500)[0]))


if __name__ == "__main__":
    main()
