"""Phase 2: bigram baseline.

1. Count every pair of consecutive characters -> the best possible bigram.
2. Train a (V, V) table by gradient descent and watch it approach that number.
3. Peek inside the learned table, generate text and plot the loss curve.

Usage:
    .venv/bin/python -m scripts.phase2 --device cpu
"""

import argparse
import math
import time
from dataclasses import dataclass

import torch

from curupira.dataset import get_batch, load_data, pick_device
from curupira.models.bigram import BigramLM
from curupira.plots import save_both_themes
from curupira.training import LossPoint, estimate_loss


@dataclass(frozen=True)
class Args:
    device: str
    batch_size: int
    block_size: int
    steps: int
    lr: float
    eval_every: int
    eval_iters: int
    seed: int


def parse_args() -> Args:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--device", default="auto")
    p.add_argument("--batch-size", type=int, default=32)
    p.add_argument("--block-size", type=int, default=128)
    p.add_argument("--steps", type=int, default=3000)
    p.add_argument("--lr", type=float, default=50.0, help="learning rate (plain SGD, no momentum)")
    p.add_argument("--eval-every", type=int, default=300)
    p.add_argument("--eval-iters", type=int, default=50)
    p.add_argument("--seed", type=int, default=1337)
    ns = p.parse_args()
    return Args(
        device=ns.device, batch_size=ns.batch_size, block_size=ns.block_size, steps=ns.steps,
        lr=ns.lr, eval_every=ns.eval_every, eval_iters=ns.eval_iters, seed=ns.seed,
    )


def section(title: str) -> None:
    print(f"\n{'=' * 70}\n{title}\n{'=' * 70}")


def count_bigram_loss(train: torch.Tensor, val: torch.Tensor, V: int) -> tuple[float, float, torch.Tensor]:
    """The best bigram: probability of b after a = count(a,b) / count(a, anything)."""
    pairs = train[:-1] * V + train[1:]  # (N-1,) each pair (a, b) encoded as one int a*V+b
    counts = torch.bincount(pairs, minlength=V * V).view(V, V).float()  # (V*V,) -> (V, V)

    probs = (counts + 1) / (counts + 1).sum(dim=1, keepdim=True)  # (V, V); +1 so no pair has prob 0

    def loss_on(data: torch.Tensor) -> float:
        p = probs[data[:-1], data[1:]]  # (N-1,) prob of each actual next char
        return float(-p.log().mean().item())

    return loss_on(train), loss_on(val), probs


def main() -> None:
    args = parse_args()
    device = pick_device(args.device)
    torch.manual_seed(args.seed)
    tok, train, val = load_data()
    V = tok.vocab_size

    # ------------------------------------------------------------------
    section("1. Reference numbers")
    uniform = math.log(V)
    count_train, count_val, _ = count_bigram_loss(train, val, V)
    print(f"uniform guess (knows nothing)      : {uniform:.4f}")
    print(f"bigram by counting  train / val    : {count_train:.4f} / {count_val:.4f}")

    # ------------------------------------------------------------------
    section(f"2. Training the (V, V) table with SGD on {device}")
    model = BigramLM(V).to(device)
    n_params = sum(p.numel() for p in model.parameters())
    print(f"parameters: {n_params:,} (= {V} x {V})")
    splits: dict[str, torch.Tensor] = {"train": train, "val": val}
    history: list[LossPoint] = []
    t0 = time.perf_counter()
    for step in range(args.steps + 1):
        if step % args.eval_every == 0:
            losses = estimate_loss(model, splits, args.batch_size, args.block_size, args.eval_iters, device)
            history.append(LossPoint(step=step, train=losses["train"], val=losses["val"]))
            print(f"step {step:>5} | train {losses['train']:.4f} | val {losses['val']:.4f} "
                  f"| {time.perf_counter() - t0:5.1f}s")
        if step == args.steps:
            break

        x, y = get_batch(train, args.batch_size, args.block_size, device)  # (B, T), (B, T)
        _, loss = model(x, y)  # forward: scalar loss
        assert loss is not None

        model.zero_grad(set_to_none=True)
        loss.backward()  # table.grad: (V, V), how the loss changes when each score changes
        with torch.no_grad():
            for p in model.parameters():
                assert p.grad is not None
                p -= args.lr * p.grad  # plain SGD: step against the gradient

    # ------------------------------------------------------------------
    section("3. Looking inside the learned table")
    learned = torch.softmax(model.table.detach().cpu(), dim=-1)  # (V, V) scores -> probabilities
    for ch in ["q", "ç", ".", "\n"]:
        i = tok.stoi[ch]
        top = torch.topk(learned[i], 5)  # values: (5,), indices: (5,)
        guesses = "  ".join(
            f"{tok.itos[j]!r} {v:.0%}" for v, j in zip(top.values.tolist(), top.indices.tolist())
        )
        print(f"after {ch!r:>5}: {guesses}")

    # ------------------------------------------------------------------
    section("4. Text generated by the bigram (500 chars)")
    torch.manual_seed(args.seed)
    start = torch.tensor([[tok.stoi["\n"]]], device=device)  # (1, 1)
    print(tok.decode(model.generate(start, 500)[0]))

    # ------------------------------------------------------------------
    section("5. Loss curve")
    save_both_themes(
        history,
        references=[("chute uniforme", uniform), ("bigram por contagem", count_val)],
        title="Bigram: a loss cai de 4,75 até o limite do que pares de letras conseguem",
        stem="phase2_loss",
        ylim=(2.1, 5.0),
    )


if __name__ == "__main__":
    main()
